# Dockerfile for building + testing the RPM under RHEL or RHEL-like env
FROM registry.access.redhat.com/ubi9/ubi:latest

# Install all build dependencies
RUN dnf install -y make gcc systemd rpm-build git shadow-utils && dnf clean all

RUN git config --global --add safe.directory /source

VOLUME /source
WORKDIR /source

ENTRYPOINT [ "/bin/bash", "-c" ]