name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v4
    - name: Install stuff for creating packages
      run: sudo apt install -y fakeroot dpkg debhelper
    - name: Install packages required for optional configurations of cntlm
      run: sudo apt install -y libkrb5-dev
    - name: Install further tools (clang-tools for scan-build)
      run: sudo apt install -y clang-tools
    - name: Normal build
      run: |
        ./configure
        make
        ./cntlm -h
        make distclean
    - name: Unicode build
      run: |
        ./configure
        CFLAGS=-DUNICODE make
        ./cntlm -h
        make distclean
    - name: Build with kerberos enabled
      run: |
        ./configure --enable-kerberos
        make
        ./cntlm -h
        make distclean
    - name: Verify debug build
      run: |
        ./configure
        make DEBUG=1
        ./cntlm -h
        make distclean
    - name: Verify debian package creation and installation
      run: |
        ./configure
        make deb
        make clean
        sudo make install
        sudo make uninstall
        make distclean
    - name: Build via scan-build
      run: |
        ./configure
        scan-build --force-analyze-debug-code make

  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - os: rhel
          image: registry.access.redhat.com/ubi9/ubi:latest
        - os: sles
          image: registry.suse.com/suse/sle15:latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Install build dependencies (RHEL)
        run: dnf install -y make gcc systemd rpm-build git shadow-utils && dnf clean all
        if: ${{ matrix.os == 'rhel' }}
      - name: Install build dependencies (SLES)
        run: zypper install -y make gcc systemd rpm-build git shadow && zypper clean -a
        if: ${{ matrix.os == 'sles' }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set working directory as safe
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Build the source
        run: |
          ./configure
          make rpm
      - name: Install the RPM
        run: 'rpm -iv cntlm*.rpm'
      - name: Invoke cNTLM to ensure it is installed properly
        run: cntlm -h
      