name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - name: Install stuff for creating packages
      run: sudo apt install -y fakeroot dpkg debhelper
    - name: Install packages required for optional configurations of cntlm
      run: sudo apt install -y libkrb5-dev
    - name: Install further tools (clang-tools for scan-build)
      run: sudo apt install -y clang-tools
    - name: Normal build
      run: |
        ./configure
        make
        ./cntlm -h
        make distclean
    - name: Unicode build
      run: |
        ./configure
        CFLAGS=-DUNICODE make
        ./cntlm -h
        make distclean
    - name: Build with kerberos enabled
      run: |
        ./configure --enable-kerberos
        make
        ./cntlm -h
        make distclean
    - name: Verify debug build
      run: |
        ./configure
        make DEBUG=1
        ./cntlm -h
        make distclean
    - name: Verify debian package creation and installation
      run: |
        ./configure
        make deb
        make clean
        sudo make install
        sudo make uninstall
        make distclean
    - name: Verify RHEL + SLES package creattion and installation
      run: |
        docker build -f containers/Dockerfile.rhel -t localhost/cntlm-rpm-packaging:rhel .
        docker build -f containers/Dockerfile.sles -t localhost/cntlm-rpm-packaging:sles .
        docker run -v .:/source localhost/cntlm-rpm-packaging:rhel './configure && make rpm && rpm -iv cntlm*.rpm && cntlm -h'
        make distclean
        docker run -v .:/source localhost/cntlm-rpm-packaging:sles './configure && make rpm && rpm -iv cntlm*.rpm && cntlm -h'
    - name: Build via scan-build
      run: |
        ./configure
        scan-build --force-analyze-debug-code make